ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SENIOR_TECHNICIAN';

ALTER TYPE "AppModule" ADD VALUE IF NOT EXISTS 'KANBAN_EDIT_TITLE';
ALTER TYPE "AppModule" ADD VALUE IF NOT EXISTS 'KANBAN_EDIT_DUE_DATE';
ALTER TYPE "AppModule" ADD VALUE IF NOT EXISTS 'KANBAN_EDIT_TRACK';
ALTER TYPE "AppModule" ADD VALUE IF NOT EXISTS 'KANBAN_MANAGE_ASSIGNEES';
ALTER TYPE "AppModule" ADD VALUE IF NOT EXISTS 'KANBAN_MANAGE_PARTICIPANTS';
ALTER TYPE "AppModule" ADD VALUE IF NOT EXISTS 'KANBAN_MOVE_TO_OTHER_BOARD';
