-- Раздельные права на типы уведомлений по нарядам
ALTER TYPE "AppModule" ADD VALUE IF NOT EXISTS 'ORDERS_NOTIFICATIONS_ADMIN';
ALTER TYPE "AppModule" ADD VALUE IF NOT EXISTS 'ORDERS_NOTIFICATIONS_CORRECTIONS';
ALTER TYPE "AppModule" ADD VALUE IF NOT EXISTS 'ORDERS_NOTIFICATIONS_PROSTHETICS';
